"""Fixtures shared by the whole test suite.

The ERA5 test data exists in both storage formats RESKit reads: as the netCDF4 files of
``era5/`` and ``era5-csp/``, and as Zarr stores in ``era5-zarr/`` holding the same data,
generated by ``scripts/make_era5_zarr_test_data.py``. A test which takes ``era5_path``,
``era5_csp_path`` or ``era5_source_class`` therefore runs once per format, with the
same expected values -- for ``era5_csp_path`` only if it reads with
``time_index_from="direct_horizontal_irradiance"``, see there.
"""

import pytest

from reskit import TEST_DATA
from reskit.weather import Era5Source, Era5ZarrSource

ERA5_PATHS = {
    "netcdf": TEST_DATA["era5"],
    "zarr": TEST_DATA["era5.zarr"],
}
ERA5_CSP_PATHS = {
    "netcdf": TEST_DATA["era5-csp"],
    "zarr": TEST_DATA["era5-csp.zarr"],
}
ERA5_SOURCE_CLASSES = {
    "netcdf": Era5Source,
    "zarr": Era5ZarrSource,
}


@pytest.fixture(params=["netcdf", "zarr"])
def era5_format(request) -> str:
    """The storage format of the ERA5 test data, 'netcdf' or 'zarr'."""
    return request.param


@pytest.fixture
def era5_path(era5_format) -> str:
    """The 'era5' test data, as a directory of netCDF4 files or as a Zarr store."""
    return ERA5_PATHS[era5_format]


@pytest.fixture
def era5_csp_path(era5_format) -> str:
    """The 'era5-csp' test data, as a directory of netCDF4 files or as a Zarr store.

    The radiation file of 'era5-csp' is labelled one hour later than the other two.
    Era5Source takes the time axis of one file -- the first, unless 'time_index_from'
    names another -- while the Zarr store has the radiation's axis. Both formats
    therefore yield the same time index only when read with
    time_index_from="direct_horizontal_irradiance", as csp_ptr_era5 does; without it
    the netCDF4 time index starts one hour earlier.
    """
    return ERA5_CSP_PATHS[era5_format]


@pytest.fixture
def era5_source_class(era5_format) -> type[Era5Source]:
    """The ERA5 source which reads the format of 'era5_path'."""
    return ERA5_SOURCE_CLASSES[era5_format]
