from collections import OrderedDict

import geokit as gk
import numpy as np

from reskit.util import ResError


def apply_logarithmic_profile_projection(
    measured_wind_speed,
    measured_height,
    target_height,
    roughness,
    displacement=0,
    stability=0,
):
    """
    Estimates wind speeds at a target height based on measured wind speeds values at a known measurement height.
    Estimation is subject to surface roughness, displacement height, and a stability factor.

    Parameters
    ----------
    measured_wind_speed : numeric or array-like
        The input wind speeds in m/s that are going to be adjusted
        If an array is given with a single dimension, it is assumed to represent timeseries values for a single location
        If multidimensional array is given, the assumed dimensional context is (time, locations).

    measured_height : numeric or array-like
        The measurement height in m of the input wind speeds.
        Must either be a single value, or an array of values with the same length as the "locations" dimension of `measured_wind_speed`

    target_height : numeric or array-like
        The height in m to project each wind speed timeseries to.
        Must either be a single value, or an array of values with the same length as the "locations" dimension of `measured_wind_speed`

    roughness : numeric or array-like
        The roughness value used to project each wind speed timeseries.
        Must either be a single value, or an array of values with the same length as the "locations" dimension of `measured_wind_speed`

    displacement : numeric or array-like, optional
        The displacement value used to project each wind speed timeseries, by default 0.
        Must either be a single value, or an array of values with the same length as the "locations" dimension of `measured_wind_speed`

    stability : numeric or array-like, optional
        The stability value used to project each wind speed timeseries, by default 0.
        Must either be a single value, or an array of values with the same length as the "locations" dimension of `measured_wind_speed`

    Returns
    -------
    multidimensional array-like
        Wind speed values in m/s at target height with of the same dimensions as `measured_wind_speed`.

    Notes
    -----
        Roughness values can be generated by the following functions:
        roughness_from_levels(low_wind_speed, low_height, high_wind_speed, high_height)
        roughness_from_clc(clc_path, loc, window_range)
        roughness_from_land_cover_classification(classification, land_cover_type)
        roughness_from_land_cover_source(source, loc, land_cover_type)


    See Also
    --------
        apply_power_profile_projection( <wind speeds, <measured height>, <target height>, <alpha> )
    """
    return (
        measured_wind_speed
        * (np.log((target_height - displacement) / roughness) + stability)
        / (np.log((measured_height - displacement) / roughness) + stability)
    )


def roughness_from_levels(low_wind_speed, low_height, high_wind_speed, high_height):
    """
    Computes a roughness factor from two windspeed values at two distinct heights.

    Parameters
    ----------
    low_wind_speed : numeric or numpy.ndarray
        The measured wind speed in m/s at the lower height.

    low_height : numeric or numpy.ndarray
        The lower height in m.

    high_wind_speed : numeric or numpy.ndarray
        The measured wind speed in m/s at the higher height.

    high_height : numeric or numpy.ndarray
        The higher height in m.

    Returns
    -------
    numeric or arrray-like
        Roughness factor

    See Also
    --------
        roughness_from_clc(clc_path, loc, window_range)
        roughness_from_land_cover_classification(classification, land_cover_type)
        roughness_from_land_cover_source(source, loc, land_cover_type)
    """
    return np.exp(
        (high_wind_speed * np.log(low_height) - low_wind_speed * np.log(high_height))
        / (high_wind_speed - low_wind_speed)
    )


############################################################################
# See CLC codes at: https://land.copernicus.eu/pan-european/corine-land-cover/clc-2000 #Link updated
# Roughnesses defined primarily from: Silva, J., Ribeiro, C., & Guedes, R. (2007). Roughness length classification of corine land cover classes. European Wind Energy Conference and Exhibition 2007, EWEC 2007.

clc_code_to_roughness = OrderedDict()
clc_code_to_roughness[111] = 1.2  # Continuous urban fabric
clc_code_to_roughness[311] = 0.75  # Broad-leaved forest
clc_code_to_roughness[312] = 0.75  # Coniferous-leaved forest
clc_code_to_roughness[313] = 0.75  # Mixed-leaved forest
clc_code_to_roughness[141] = 0.6  # Green urban areas
clc_code_to_roughness[324] = 0.6  # Transitional woodland/shrub
clc_code_to_roughness[334] = 0.6  # Burnt areas
clc_code_to_roughness[112] = 0.5  # Discontinuous urban fabric
clc_code_to_roughness[133] = 0.5  # Construction sites
clc_code_to_roughness[121] = 0.5  # Industrial or commercial units
clc_code_to_roughness[142] = 0.5  # Sport and leisure facilities
clc_code_to_roughness[123] = 0.5  # Port areas
clc_code_to_roughness[242] = 0.3  # Agro-forestry areas
clc_code_to_roughness[243] = 0.3  # Complex cultivation patterns
# Land principally occupied by agriculture, with significant areas of natural vegetation
clc_code_to_roughness[244] = 0.3
clc_code_to_roughness[241] = 0.1  # Annual crops associated with permanent crops
clc_code_to_roughness[221] = 0.1  # Fruit trees and berry plantations
clc_code_to_roughness[222] = 0.1  # Vineyard
clc_code_to_roughness[223] = 0.1  # Olive groves
clc_code_to_roughness[122] = 0.075  # Road and rail networks and associated land
clc_code_to_roughness[211] = 0.05  # Non-irrigated arable land
clc_code_to_roughness[212] = 0.05  # Permanently irrigated land
clc_code_to_roughness[213] = 0.05  # Rice fields
clc_code_to_roughness[411] = 0.05  # Inland marshes
clc_code_to_roughness[421] = 0.05  # Salt marshes
clc_code_to_roughness[321] = 0.03  # Sclerophylous vegetation
clc_code_to_roughness[322] = 0.03  # Moors and heathland
clc_code_to_roughness[323] = 0.03  # Natural grassland
clc_code_to_roughness[231] = 0.03  # Pastures
clc_code_to_roughness[131] = 0.005  # Dump sites
clc_code_to_roughness[132] = 0.005  # Mineral extraction sites
clc_code_to_roughness[124] = 0.005  # Airports
clc_code_to_roughness[332] = 0.005  # Bare rock
clc_code_to_roughness[333] = 0.005  # Sparsely vegetated areas
clc_code_to_roughness[335] = 0.001  # Glaciers and perpetual snow
clc_code_to_roughness[422] = 0.0005  # Peatbogs
clc_code_to_roughness[412] = 0.0005  # Salines
clc_code_to_roughness[423] = 0.0005  # Intertidal flats
clc_code_to_roughness[331] = 0.0003  # Beaches, dunes, and sand plains
clc_code_to_roughness[511] = 0.001  # Water courses # SUSPICIOUS
clc_code_to_roughness[512] = 0.0005  # Water bodies # SUSPISCIOUS
clc_code_to_roughness[521] = 0.0005  # Costal lagoons # SUSPISCIOUS
clc_code_to_roughness[522] = 0.0008  # Estuaries # SUSPISCIOUS
clc_code_to_roughness[523] = 0.0002  # Sea and ocean # SUSPISCIOUS

clc_grid_to_code_v2006 = OrderedDict()
clc_grid_to_code_v2006[1] = 111
clc_grid_to_code_v2006[2] = 112
clc_grid_to_code_v2006[3] = 121
clc_grid_to_code_v2006[4] = 122
clc_grid_to_code_v2006[5] = 123
clc_grid_to_code_v2006[6] = 124
clc_grid_to_code_v2006[7] = 131
clc_grid_to_code_v2006[8] = 132
clc_grid_to_code_v2006[9] = 133
clc_grid_to_code_v2006[10] = 141
clc_grid_to_code_v2006[11] = 142
clc_grid_to_code_v2006[12] = 211
clc_grid_to_code_v2006[13] = 212
clc_grid_to_code_v2006[14] = 213
clc_grid_to_code_v2006[15] = 221
clc_grid_to_code_v2006[16] = 222
clc_grid_to_code_v2006[17] = 223
clc_grid_to_code_v2006[18] = 231
clc_grid_to_code_v2006[19] = 241
clc_grid_to_code_v2006[20] = 242
clc_grid_to_code_v2006[21] = 243
clc_grid_to_code_v2006[22] = 244
clc_grid_to_code_v2006[23] = 311
clc_grid_to_code_v2006[24] = 312
clc_grid_to_code_v2006[25] = 313
clc_grid_to_code_v2006[26] = 321
clc_grid_to_code_v2006[27] = 322
clc_grid_to_code_v2006[28] = 323
clc_grid_to_code_v2006[29] = 324
clc_grid_to_code_v2006[30] = 331
clc_grid_to_code_v2006[31] = 332
clc_grid_to_code_v2006[32] = 333
clc_grid_to_code_v2006[33] = 334
clc_grid_to_code_v2006[34] = 335
clc_grid_to_code_v2006[35] = 411
clc_grid_to_code_v2006[36] = 412
clc_grid_to_code_v2006[37] = 421
clc_grid_to_code_v2006[38] = 422
clc_grid_to_code_v2006[39] = 423
clc_grid_to_code_v2006[40] = 511
clc_grid_to_code_v2006[41] = 512
clc_grid_to_code_v2006[42] = 521
clc_grid_to_code_v2006[43] = 522
clc_grid_to_code_v2006[44] = 523


def roughness_from_clc(clc_path, loc, window_range=0):
    """
    Estimates a roughness factor according to suggestions by Silva et al. [1] by the prominent land cover at given locations according to the Corine Land Cover dataset [2].

    Parameters
    ----------
    clc_path : str
        The path to the Corine Land Cover (CLC) raster file on the disk.
        This function currently only works for CLC versions before 2018.

    loc : Anything acceptable to geokit.LocationSet
        The locations for which roughness should be estimated.
        Arguments accepted include: str, OGR point object (must have an SRS within the object, default = 4326 (for Europe)), lat and lon coordinates tuple (lat,lon).
        Refers to https://github.com/FZJ-IEK3-VSA/geokit/blob/master/geokit/core/location.py for more information.

    window_range : int; optional
        An extra number of pixels to extract around the indicated locations, by default 0.
        A window_range = 0 means that only the CLC pixel value for each location is returned. A window_range of 1 means an extra pixel is extracted around each location in all directions. Leading to a 3x3 matrix of roughness values
        Use this if you need to do some operation on the roughnesses found around the indicated location

    Returns
    -------
    float or numpy.ndarray
        Roughness lengths factors
        A single float is returned in the event that a single location is specified in `locations`.
        A one-dimensional Numpy array is returned in the event that multiple locations are specified in `locations`.


    See Also
    --------
        roughness_from_levels(low_wind_speed, low_height, high_wind_speed, high_height)
        roughness_from_land_cover_classification(classification, land_cover_type)
        roughness_from_land_cover_source(source, loc, land_cover_type)

    Sources
    --------
        [1] Silva, J., Ribeiro, C., & Guedes, R. (2007). Roughness length classification of corine land cover classes. European Wind Energy Conference and Exhibition 2007, EWEC 2007.
        [2] Copernicus (European Union’s Earth Observation Programme). (2018). Corine Land Cover (CLC) 2000, Version 2018. Copernicus. http://land.copernicus.eu/pan-european/corine-land-cover/clc-2000/view

    Roughness values [1]
    --------------------

        Continuous urban fabric : 1.2
        Broad-leaved forest : 0.75
        Coniferous-leaved forest : 0.75
        Mixed-leaved forest : 0.75
        Green urban areas : 0.6
        Transitional woodland/shrub : 0.6
        Burnt areas : 0.6
        Discontinuous urban fabric : 0.5
        Construction sites : 0.5
        Industrial or commercial units : 0.5
        Sport and leisure facilities : 0.5
        Port areas : 0.5
        Agro-forestry areas : 0.3
        Complex cultivation patterns : 0.3
        Land principally occupied by agriculture, with significant areas of natural vegetation : 0.3
        Annual crops associated with permanent crops : 0.1
        Fruit trees and berry plantations : 0.1
        Vineyard : 0.1
        Olive groves : 0.1
        Road and rail networks and associated land : 0.075
        Non-irrigated arable land : 0.05
        Permanently irrigated land : 0.05
        Rice fields : 0.05
        Inland marshes : 0.05
        Salt marshes : 0.05
        Sclerophylous vegetation : 0.03
        Moors and heathland : 0.03
        Natural grassland : 0.03
        Pastures : 0.03
        Dump sites : 0.005
        Mineral extraction sites : 0.005
        Airports : 0.005
        Bare rock : 0.005
        Sparsely vegetated areas : 0.005
        Glaciers and perpetual snow : 0.001
        Peatbogs : 0.0005
        Salines : 0.0005
        Intertidal flats : 0.0005
        Beaches, dunes, and sand plains : 0.0003
        Water courses # SUSPICIOUS : 0.001
        Water bodies # SUSPISCIOUS : 0.0005
        Costal lagoons # SUSPISCIOUS : 0.0005
        Estuaries # SUSPISCIOUS : 0.0008
        Sea and ocean # SUSPISCIOUS : 0.0002

    """
    # Ensure location is okay
    loc = gk.LocationSet(loc)

    # Get pixels values from clc
    clc_grid_values = gk.raster.interpolateValues(clc_path, loc, winRange=window_range, noDataOkay=True)

    # make output array
    if window_range > 0:
        outputs = []
        for v in clc_grid_values:
            # Treat nodata as ocean
            v[np.isnan(v)] = 44
            v[v > 44] = 44
            v = v.astype(int)

            values, counts = np.unique(v, return_counts=True)

            total = 0
            for val, cnt in zip(values, counts):
                total += cnt * clc_code_to_roughness[clc_grid_to_code_v2006[val]]

            outputs.append(total / counts.sum())
    else:
        # Treat nodata as ocean
        clc_grid_values[np.isnan(clc_grid_values)] = 44
        clc_grid_values[clc_grid_values > 44] = 44
        clc_grid_values = clc_grid_values.astype(int)

        # Get the associated
        outputs = [clc_code_to_roughness[clc_grid_to_code_v2006[val]] for val in clc_grid_values]

    # Done!
    if len(outputs) == 1:
        return outputs[0]
    else:
        return np.array(outputs)


############################################################################
# Defined primarily from [2] DTU Wind Energy. (2019). Global Wind Atlas
glob_cover_code_to_roughness = OrderedDict()
# GlobCover Number
# Water Bodies # changed by Me from 0.0 to 0.0002
glob_cover_code_to_roughness[210] = 0.0002
glob_cover_code_to_roughness[220] = 0.0004  # Permanent Snow and ice
glob_cover_code_to_roughness[200] = 0.005  # Bare areas
glob_cover_code_to_roughness[140] = 0.03  # Grasslands, savannas or lichens/mosses
glob_cover_code_to_roughness[150] = 0.05  # Sparse vegetation
glob_cover_code_to_roughness[11] = 0.1  # Croplands
glob_cover_code_to_roughness[14] = 0.1  # Croplands
glob_cover_code_to_roughness[130] = 0.1  # Shrubland
glob_cover_code_to_roughness[180] = 0.2  # Wetlands
glob_cover_code_to_roughness[20] = 0.3  # Mosaic natural vegetation/cropland
glob_cover_code_to_roughness[30] = 0.3  # Mosaic natural vegetation/cropland
glob_cover_code_to_roughness[160] = 0.5  # Flooded forest
glob_cover_code_to_roughness[120] = 0.5  # Mosaic grassland/forest
glob_cover_code_to_roughness[170] = 0.6  # Flooded forest or shrubland
glob_cover_code_to_roughness[190] = 1.0  # Urban Areas
glob_cover_code_to_roughness[40] = 1.5  # Forests
glob_cover_code_to_roughness[50] = 1.5  # Forests
glob_cover_code_to_roughness[60] = 1.5  # Forests
glob_cover_code_to_roughness[70] = 1.5  # Forests
glob_cover_code_to_roughness[90] = 1.5  # Forests
glob_cover_code_to_roughness[100] = 1.5  # Forests
glob_cover_code_to_roughness[110] = 1.5  # Forests

# Modis Number for "no data" points of GlobCover (mostly in areas North of 60°)
modis_code_to_roughness = OrderedDict()
modis_code_to_roughness[0] = 0.0  # Water Bodies
modis_code_to_roughness[15] = 0.0004  # Permanent Snow and ice
modis_code_to_roughness[16] = 0.005  # Bare areas
modis_code_to_roughness[10] = 0.03  # Grasslands, savannas or lichens/mosses
modis_code_to_roughness[12] = 0.1  # Croplands
modis_code_to_roughness[6] = 0.1  # Shrubland
modis_code_to_roughness[7] = 0.1  # Shrubland
modis_code_to_roughness[11] = 0.2  # Wetlands
modis_code_to_roughness[14] = 0.3  # Mosaic natural vegetation/cropland
modis_code_to_roughness[9] = 0.5  # Mosaic grassland/forest
modis_code_to_roughness[13] = 1.0  # Urban Areas
modis_code_to_roughness[1] = 1.5  # Forests
modis_code_to_roughness[2] = 1.5  # Forests
modis_code_to_roughness[3] = 1.5  # Forests
modis_code_to_roughness[4] = 1.5  # Forests
modis_code_to_roughness[5] = 1.5  # Forests
modis_code_to_roughness[8] = 1.5  # Forests

############################################################################
# CCI Landcover  classification by ESA and the Climate Change Initiative [3] European Space Agency. (2014). ESA Climate Change Initiative. https://www.esa-landcover-cci.org/?q=node/1
# Roughnesses defined due to the comparison with CLC and globCover
cci_code_to_roughness = OrderedDict()
# CCI LC Number
cci_code_to_roughness[210] = 0.0002  # Water bodies
cci_code_to_roughness[220] = 0.001  # Permanent snow and ice
cci_code_to_roughness[200] = 0.005  # Bare areas
cci_code_to_roughness[201] = 0.005  # Consolidated bare areas
cci_code_to_roughness[202] = 0.005  # Unconsolidated bare areas
# Sparse vegetation (tree, shrub, herbaceous cover) (<15%)
cci_code_to_roughness[150] = 0.005
cci_code_to_roughness[151] = 0.005  # Sparse tree (<15%)
cci_code_to_roughness[152] = 0.005  # Sparse shrub (<15%)
cci_code_to_roughness[153] = 0.005  # Sparse herbaceous cover (<15%)
cci_code_to_roughness[10] = 0.03  # Cropland, rainfed
cci_code_to_roughness[11] = 0.03  # Herbaceous cover
cci_code_to_roughness[120] = 0.03  # Shrubland
# Shrubland evergreen #barely exists, only near water bodies, ocean
cci_code_to_roughness[121] = 0.03
# Shrubland deciduous #barely exists, only near water bodies, ocean
cci_code_to_roughness[122] = 0.03
cci_code_to_roughness[12] = 0.3  # Tree or shrub cover
# Mosaic herbaceous cover (>50%) / tree and shrub (<50%)
cci_code_to_roughness[110] = 0.03
# Mosaic natural vegetation (tree, shrub, herbaceous cover) (>50%) / cropland (<50%)
cci_code_to_roughness[40] = 0.03
# Shrub or herbaceous cover, flooded, fresh/saline/brakish water
cci_code_to_roughness[180] = 0.03
cci_code_to_roughness[130] = 0.03  # Grassland
cci_code_to_roughness[140] = 0.03  # Lichens and mosses
# Tree cover, flooded, saline water (areas around river deltas and ocean)
cci_code_to_roughness[170] = 0.1
cci_code_to_roughness[20] = 0.1  # Cropland, irrigated or post-flooding
# Mosaic cropland (>50%) / natural vegetation (tree, shrub, herbaceous cover) (<50%)
cci_code_to_roughness[30] = 0.1
# Tree cover, flooded, fresh or brakish water, barely exists
cci_code_to_roughness[160] = 0.5
# Mosaic tree and shrub (>50%) / herbaceous cover (<50%)
cci_code_to_roughness[100] = 0.75
# Tree cover, broadleaved, evergreen, closed to open (>15%)
cci_code_to_roughness[50] = 0.75
# Tree cover, broadleaved, deciduous, closed to open (>15%)
cci_code_to_roughness[60] = 0.75
# Tree cover, broadleaved, deciduous, closed (>40%)
cci_code_to_roughness[61] = 0.75
# Tree cover, broadleaved, deciduous, open (15-40%)
cci_code_to_roughness[62] = 0.75
# Tree cover, needleleaved, evergreen, closed to open (>15%)
cci_code_to_roughness[70] = 0.75
# Tree cover, needleleaved, evergreen, closed (>40%)
cci_code_to_roughness[71] = 0.75
# Tree cover, needleleaved, evergreen, open (15-40%)
cci_code_to_roughness[72] = 0.75
# Tree cover, needleleaved, deciduous, closed to open (>15%)
cci_code_to_roughness[80] = 0.75
# Tree cover, needleleaved, deciduous, closed (>40%)
cci_code_to_roughness[81] = 0.75
# Tree cover, needleleaved, deciduous, open (15-40%)
cci_code_to_roughness[82] = 0.75
# Tree cover, mixed leaf type (broadleaved and needleleaved)
cci_code_to_roughness[90] = 0.75
cci_code_to_roughness[190] = 1.2  # Urban areas


def roughness_from_land_cover_classification(classification, land_cover_type="clc"):
    """
    Estimates roughness value from land cover classifications

    Parameters
    ----------
    classification : int
        land cover classification

    land_cover_type : str, optional
        Accepted arguments are 'clc', 'clc-code', 'globCover', 'modis', or 'cci', by default 'clc'
        'clc': Corine Land Cover (CLC)
        'clc-code': Corine Land Cover (CLC) codes values
        'globCover': Global Wind Atlas roughness lengths values
        'modis': Modis number for "no data" points of Global Wind Atlas (mostly in areas North of 60°)
        'cci': Climate Change Initiative land cover classification

    Returns
    -------
    int or numpy.ndarray
        Roughness lengths factors
        A single int is returned in the event that a single location is specified in `locations`.
        A one-dimensional Numpy array is returned in the event that multiple locations are specified in `locations`.

    See Also
    --------
        roughness_from_levels(low_wind_speed, low_height, high_wind_speed, high_height)
        roughness_from_clc(clc_path, loc, window_range)
        roughness_from_land_cover_source(source, loc, land_cover_type)

    """
    if land_cover_type == "clc":
        # fix no data values
        classification[classification < 0] = 44
        classification[classification > 44] = 44
        classification[np.isnan(classification)] = 44

        # set source
        def source(x):
            return clc_code_to_roughness[clc_grid_to_code_v2006[x]]

    elif land_cover_type == "clc-code":

        def source(x):
            return clc_code_to_roughness[x]

    elif land_cover_type == "globCover":

        def source(x):
            return glob_cover_code_to_roughness[x]

    elif land_cover_type == "modis":

        def source(x):
            return modis_code_to_roughness[x]

    elif land_cover_type == "cci":

        def source(x):
            return cci_code_to_roughness[x]

    else:
        raise ResError(f"invalid input for land_cover_type: {land_cover_type}")

    converter = np.vectorize(source)
    return converter(classification)


def roughness_from_land_cover_source(source, loc, land_cover_type="clc"):
    """
    Estimate roughness value from a given land cover raster source

    Parameters
    ----------
    source : str
        The path to the Corine Land Cover raster file on the disk.

    loc : Anything acceptable to geokit.LocationSet
        Arguments accepted include: str, OGR point object (must have an SRS within the object, default = 4326 (for Europe)), lat and lon coordinates (tuple (lat,lon)).
        Refers to https://github.com/FZJ-IEK3-VSA/geokit/blob/master/geokit/core/location.py for more information.

    land_cover_type : str, optional
        Accepted arguments are 'clc', 'clc-code', 'globCover', 'modis', or 'cci', by default 'clc'
        'clc': Corine Land Cover (CLC)
        'clc-code': Corine Land Cover (CLC) codes
        'globCover': Global Wind Atlas
        'modis': Modis number for "no data" points of Global Wind Atlas (mostly in areas North of 60°)
        'cci': Climate Change Initiative land cover classification

    Returns
    -------
    int or numpy.ndarray
        Roughness lengths factors
        A single int is returned in the event that a single location is specified in `locations`.
        A one-dimensional Numpy array is returned in the event that multiple locations are specified in `locations`.

    See Also
    --------
        roughness_from_levels(low_wind_speed, low_height, high_wind_speed, high_height)
        roughness_from_clc(clc_path, loc, window_range)
        roughness_from_land_cover_classification(classification, land_cover_type)
    """
    loc = gk.LocationSet(loc)
    classifications = gk.raster.interpolateValues(source, loc, noDataOkay=False)

    return roughness_from_land_cover_classification(classifications, land_cover_type=land_cover_type)
