image: continuumio/miniconda3:latest

stages:
  - test

test:
  stage: test
  tags: 
   - linux

  script: 
    - conda install mamba -c conda-forge
    - mamba create -n reskit
    - source activate reskit
    - git clone --branch dev https://CIGlaes:${GeokitAccessToken}@jugit.fz-juelich.de/iek-3/shared-code/geokit.git
    - cd geokit
    - mamba env update -n reskit --file=requirements-dev.yml
    - cd ..
    - mamba env update -n reskit --file=requirements-dev.yml
    - python -m pip install -e .
    - python -m pytest --cov=reskit test/