image: mambaorg/micromamba

stages:
  - test

.test_template:
  stage: test
  before_script:
    # create environment
    - micromamba create -y -n reskit --file=requirements-dev.yml
    - eval "$(micromamba shell hook --shell bash)"
    - micromamba activate reskit
    # Install reskit in editable mode
    - python -m pip install -e . --no-deps

test-code:
  extends: .test_template
  script:
    # Test code
    - python -m pytest --cov=reskit test/
