coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default       # only comment once per PR, update in place
  require_changes: false   # don't comment if nothing changed
