name: reskit_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - matplotlib
  - descartes
  - pandas<2.0.0
  - openpyxl
  - numpy
  - numba
  - scipy
  - scikit-learn
  - geokit>=1.4.0
  - gdal=3.4.*
  - netCDF4>=1.5.3
  - xarray
  - pvlib-python=0.9.0
  - windpowerlib