name: reskit
channels:
  - conda-forge
  - pvlib
dependencies:
  - python
  - pip
  - matplotlib
  - descartes
  - pandas
  - openpyxl
  - numpy
  - numba
  - scipy
  - scikit-learn
  - geokit>=1.4.0
  - gdal=3.4.*
  - netCDF4>=1.5.3
  - xarray
  - pvlib=0.9.0
