
line-length = 120
[lint.pycodestyle]
max-doc-length = 120
max-line-length = 120

[lint]
select = ["D", "F","TID","I","N"]
ignore = [
    "F401", # imported but unused
    "F405", # Variable is undefined or from star import
    "F403", #  `from test.helpers import *` used; unable to detect undefined names
    "F811", # Redefinition of unused variable
    "F541", # f-string without any placeholders
    "F841", # variable is assigned to but never used
    "F821", # Undefined name `plt`
    "E711", # Comparison to `None` should be `is None`
    "E712", # Avoid equality comparisons to `False`; use `not l1 == l3:` for false checks
    "E713", # Test for membership should be `not in`
    "E714", # [*] Test for object identity should be `is not`
    "E741", # Ambiguous variable name: `l`
    "E722", # Do not use bare `except`
    "D401", # First line of docstring should be in imperative mood: "Runs the EGSworkflow and returns the output.
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D103", # Missing docstring in public function
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D200", # One-line docstring should fit on one line
    "D205", # blank line required between summary line and description
    "D301", # Use `r"""` if any backslashes in a docstring
    "D400", # First line should end with a period
    "D404", # First word of the docstring should not be "This"
    "N813", # Camelcase `netCDF4` imported as lowercase `nc
]
unfixable = ["F401"]

[lint.pydocstyle]
convention = "numpy"

[format]
docstring-code-format = true
docstring-code-line-length = 20
