"""The Zarr ERA5 test data must hold exactly the data of the netCDF4 test data.

The stores are generated by scripts/make_era5_zarr_test_data.py; if one of these
tests fails after a netCDF4 fixture changed, rerun that script.
"""

from glob import glob
from os import sep
from os.path import join

import netCDF4 as nc
import numpy as np
import pytest
import xarray as xr

from reskit import TEST_DATA
from reskit.weather import Era5Source, Era5ZarrSource

# store -> the netCDF4 files it mirrors, and the variable whose time axis it takes
# where the files disagree (None: they all share one)
STORES = {
    "era5.zarr": (join(TEST_DATA["era5"], "*.nc"), None),
    "era5-csp.zarr": (join(TEST_DATA["era5-csp"], "*.nc"), "fdir_t_adj"),
}
COORDINATES = ("time", "latitude", "longitude")


@pytest.mark.parametrize("store", STORES)
def test_zarr_store_holds_the_netcdf_data(store):
    """Every variable, as Era5Source reads it from the netCDF4 files, i.e. by position."""
    files = sorted(glob(STORES[store][0]))
    assert files

    with xr.open_zarr(TEST_DATA[store]) as zarr_data:
        expected_variables = set()
        for path in files:
            with nc.Dataset(path) as netcdf_data:
                assert np.array_equal(zarr_data["latitude"].values, netcdf_data["latitude"][:])
                assert np.array_equal(zarr_data["longitude"].values, netcdf_data["longitude"][:])
                for name, variable in netcdf_data.variables.items():
                    if name in COORDINATES:
                        continue
                    expected_variables.add(name)
                    expected = np.ma.filled(variable[:].astype("float64"), np.nan)
                    assert np.array_equal(zarr_data[name].values, expected, equal_nan=True), name

        assert set(zarr_data.data_vars) == expected_variables


@pytest.mark.parametrize("store", STORES)
def test_zarr_store_has_the_time_axis_era5source_reads(store):
    """The time axis of the 'time_axis_from' variable, or the one all files share.

    A variable whose own file is labelled differently is put on that axis by position
    and keeps its first original timestamp in 'reskit_original_time_start'.
    """
    pattern, time_axis_from = STORES[store]
    files = sorted(glob(pattern))

    with xr.open_zarr(TEST_DATA[store]) as zarr_data:
        for path in files:
            with xr.open_dataset(path) as netcdf_data:
                own_axis = netcdf_data["time"].values
                assert own_axis.size == zarr_data["time"].size
                for name in netcdf_data.data_vars:
                    if time_axis_from is None or name == time_axis_from:
                        assert np.array_equal(zarr_data["time"].values, own_axis), name
                    if np.array_equal(zarr_data["time"].values, own_axis):
                        assert "reskit_original_time_start" not in zarr_data[name].attrs, name
                    else:
                        assert zarr_data[name].attrs["reskit_original_time_start"] == str(own_axis[0])[:19], name


def test_era5_csp_formats_share_the_time_index_only_with_time_index_from():
    """The documented caveat of the 'era5_csp_path' fixture (see test/conftest.py)."""
    netcdf = Era5Source(TEST_DATA["era5-csp"], verbose=False)
    zarr = Era5ZarrSource(TEST_DATA["era5-csp.zarr"], verbose=False)
    assert (zarr.time_index - netcdf.time_index == np.timedelta64(1, "h")).all()

    netcdf = Era5Source(TEST_DATA["era5-csp"], time_index_from="direct_horizontal_irradiance", verbose=False)
    zarr = Era5ZarrSource(TEST_DATA["era5-csp.zarr"], time_index_from="direct_horizontal_irradiance", verbose=False)
    assert (zarr.time_index == netcdf.time_index).all()


def test_zarr_stores_are_registered_as_single_fixtures():
    """Under their relative path and their bare name, while the files inside them are not."""
    assert (
        TEST_DATA["era5.zarr"] == TEST_DATA[join("era5-zarr", "era5.zarr")] == join(TEST_DATA["era5-zarr"], "era5.zarr")
    )
    assert not [key for key in TEST_DATA if ".zarr" + sep in key]
