"""MkDocs hooks for ETHOS.RESKit documentation.

Hooks run before plugins, so files copied here are visible to
mkdocs-jupyter for proper notebook → HTML conversion.

The example notebooks deliberately stay at the repository root in ``examples/``:
the README's installation instructions tell users to clone the repo and run them
from there, and the README links to them at that path. MkDocs can only serve
files under ``docs_dir``, so they are staged into ``docs/examples/`` here rather
than moved. The staged copy is gitignored.
"""

import shutil
from pathlib import Path

EXAMPLES_SRC = Path("examples")
EXAMPLES_DST = Path("docs/examples")

# Compared against `Path.suffix.lower()` — the match must be case-insensitive,
# so that assets committed with an uppercase suffix (e.g. ".PNG") are staged
# too. A case-sensitive check silently skips them, and the images then 404 on
# the built site while still resolving on a case-insensitive local filesystem.
COPY_EXTENSIONS = {
    ".ipynb",
    ".xlsx",
    ".csv",
    ".png",
    ".jpg",
    ".jpeg",
    ".svg",
    ".json",
    ".nc",
    ".tif",
    ".tiff",
    ".yaml",
    ".yml",
    ".shp",
    ".shx",
    ".dbf",
    ".prj",
}


def on_pre_build(config) -> None:
    """Copy example notebooks and data files into docs/examples/ before the build.

    This must happen as a hook (not via gen-files) so that mkdocs-jupyter can
    see the .ipynb files during its on_files event and render them to HTML.
    """
    for src in sorted(EXAMPLES_SRC.rglob("*")):
        if ".ipynb_checkpoints" in src.parts:
            continue
        if src.is_file() and src.suffix.lower() in COPY_EXTENSIONS:
            dst = EXAMPLES_DST / src.relative_to(EXAMPLES_SRC)
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)


# Pages whose real source lives at the repository ROOT rather than under docs/.
# `edit_uri` is "edit/dev/docs/" because most pages are docs content, so MkDocs
# prefixes every edit URL with "docs/". For these three the prefix is wrong and
# the resulting link 404s on GitHub:
#   README.md   -> the home page, generated by docs/scripts/gen_index_from_readme.py
#   reskit/     -> the API reference, generated by docs/scripts/gen_ref_pages.py
#   examples/   -> the notebooks, staged into docs/examples/ by on_pre_build above
ROOT_SOURCED_PREFIXES = ("README.md", "reskit/", "examples/")

_DOCS_SEGMENT = "/docs/"


def on_page_context(context, page, config, nav):
    """Point "Edit this page" at where each page's source really lives.

    Strips the ``docs/`` segment from the edit URL of pages whose source sits at
    the repository root (see ROOT_SOURCED_PREFIXES). Pages that genuinely live
    under ``docs/`` are left alone.
    """
    if not page.edit_url:
        return context

    index = page.edit_url.find(_DOCS_SEGMENT)
    if index == -1:
        return context

    tail = page.edit_url[index + len(_DOCS_SEGMENT) :]
    if tail.startswith(ROOT_SOURCED_PREFIXES):
        # Keep the leading slash of "/docs/", drop the "docs/" itself.
        page.edit_url = page.edit_url[: index + 1] + tail.replace(" ", "%20")
    return context
