name: Push master to Jugit

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: 
        repository: FZJ-IEK3-VSA/RESKit
    - name: Push To Gitlab
      env: 
        token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
      run: |
        echo Starting to push repo to gitlab
        git config user.name "julian-belina-auto-commit"
        git config user.email "j.belina@fz-juelich.de"
        echo user name and email are set
        git fetch
        git switch master
        echo "Checkout complete"
        echo start to push
        git push --force https://push_to_jugit:${{ secrets.GITLAB_ACCESS_TOKEN }}@jugit.fz-juelich.de/iek-3/shared-code/RESKit.git master
        echo push done
