on:
  workflow_dispatch:
  push:
    branches: ["202-test-valid-dependency-range-for-reskit-43"]
  pull_request:
    branches: ["master"]

jobs:
  TestPushCondaForgeDev:
    strategy:
      fail-fast: false
      matrix:
        runner_tag: ["self-hosted"]
        numpy_version: [
            # "0.55.0",
            # "0.55.1",
            # "0.55.2",
            # "0.56.2",
            # "0.56.3",
            # "0.56.4",
            # "0.57.0",
            # "0.57.1",
            # "0.58.1",
            # "0.59.0",
            # "0.59.1",
            # "0.60.0",
            # "0.61.0",
            "0.61.2",
            # "0.62.0",
            # "0.62.1",
          ]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
    with:
      runner_tag: ${{ matrix.runner_tag }}
      requirements_file_name: requirements-dev.yml
      library_name: "numba"
      library_version: ${{ matrix.numpy_version }}
      dependency_position_env_file: "9"
      examples_to_execute: examples/1_load_input_data/1_2_1_reading_merra_weather_data.ipynb examples/1_load_input_data/1_2_2_vertically_project_wind_speed_from_merra.ipynb examples/2_economic/ examples/3_wind examples/4_solar examples/5_geothermal/ examples/6_direct_air_capture/

  # TestOtherOSCondaForge:
  #   name: Test conda-forge development version on ${{ matrix.runner_tag }} for numba=${{ matrix.numpy_version }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       runner_tag: ["windows-latest", "macos-latest"]
  #       numpy_version: ["0.55.0"]
  #   uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
  #   with:
  #     runner_tag: ${{ matrix.runner_tag }}
  #     requirements_file_name: requirements-dev.yml
  #     library_name: "numba"
  #     library_version: ${{ matrix.numpy_version }}
  #     dependency_position_env_file: "9"
  #     examples_to_execute: examples/1_load_input_data/1_2_1_reading_merra_weather_data.ipynb examples/1_load_input_data/1_2_2_vertically_project_wind_speed_from_merra.ipynb examples/2_economic/ examples/3_wind examples/4_solar examples/5_geothermal/ examples/6_direct_air_capture/
