on:
  workflow_dispatch:
  # push:
  #   branches: ["202-test-valid-dependency-range-for-reskit-43"]
  pull_request:
    branches: ["master"]

jobs:
  TestPushCondaForgeDev:
    strategy:
      fail-fast: false
      matrix:
        runner_tag: ["self-hosted"]
        pandas_version:
          [
            "2.3.3",
            "2.3.2",
            "2.3.1",
            "2.3.0",
            "2.2.3",
            "2.2.2",
            "2.2.1",
            "2.2.0",
            "2.1.4",
            "2.1.3",
            "2.1.2",
            "2.1.1",
            "2.1.0",
            "2.0.3",
            "2.0.2",
            "2.0.1",
            "2.0.0",
            "1.5.3",
            "1.5.2",
            "1.5.1",
            "1.5.0",
            "1.4.4",
            "1.4.3",
            "1.4.2",
            "1.4.1",
            "1.4.0",
          ]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
    with:
      runner_tag: ${{ matrix.runner_tag }}
      requirements_file_name: requirements-dev.yml
      library_name: "pandas"
      library_version: ${{ matrix.pandas_version }}
      dependency_position_env_file: "6"
      examples_to_execute: examples/1_load_input_data/1_2_1_reading_merra_weather_data.ipynb examples/1_load_input_data/1_2_2_vertically_project_wind_speed_from_merra.ipynb examples/2_economic/ examples/3_wind examples/4_solar examples/5_geothermal/ examples/6_direct_air_capture/

  TestOtherOSCondaForge:
    strategy:
      fail-fast: false
      matrix:
        runner_tag: ["macos-latest", "windows-latest"]
        pandas_version: ["1.4.0"]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
    with:
      runner_tag: ${{ matrix.runner_tag }}
      requirements_file_name: requirements-dev.yml
      library_name: "pandas"
      library_version: ${{ matrix.pandas_version }}
      dependency_position_env_file: "6"
      examples_to_execute: examples/1_load_input_data/1_2_1_reading_merra_weather_data.ipynb examples/1_load_input_data/1_2_2_vertically_project_wind_speed_from_merra.ipynb examples/2_economic/ examples/3_wind examples/4_solar examples/5_geothermal/ examples/6_direct_air_capture/
