on:
  push:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  TestGeokitDevLocal:
    name: Test local development Version on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            "ubuntu-latest",
            "ubuntu-22.04",
            "macos-latest",
            "macos-14",
            "windows-latest",
            "windows-2022",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: FZJ-IEK3-VSA/RESKit
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          activate-environment: reskit_env
          conda-remove-defaults: true
      - name: Run tests
        shell: pwsh
        run: |
          ls
          echo "LS Done"
          mamba env create --name reskit_env --yes --file requirements-dev.yml
          conda run --name reskit_env pip install . --no-deps
          echo "Installation done"
          conda list --name reskit_env
          echo "libaries printed"
          echo "start pytest"
          conda run --name reskit_env pytest -vv
          echo "Pytest done"
      - name: Run Examples
        shell: pwsh
        run: |
          ls
          # Not executable in cloud without long waiting times 
          # conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/1_load_input_data/1_1_how_to_download_era5_data.ipynb
          # Requires the era 5 data which requires long waiting times
          # conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/1_load_input_data/1_2_wind_speed_from_vectors_in_era5.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/1_load_input_data/2_1_reading_merra_weather_data.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/1_load_input_data/2_2_vertically_project_wind_speed_from_merra.ipynb
          # Requires porpritiera data
          # conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/1_load_input_data/3_1_process_power_curves_from_thewindpower_net.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/2_economic/2_1_economic_compute_levelized_cost_of_electricity.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/3_wind/3_1_wind_workflows_overview.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/3_wind/3_2_1_wind_load_power_curve.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/3_wind/3_2_2_wind_synthetic_power_curve.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/3_wind/3_3_wind_convolute_a_power_curve.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/3_wind/3_4_wind_design_onshore_turbine.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/3_wind/3_5_wind_estimate_turbine_capital_cost.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/3_wind/3_6_1_wind_basic_turbine_simulation.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/3_wind/3_6_2_wind_turbine_simulation_workflow.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/3_wind/3_6_3_wind_automated_turbine_simulation_workflow.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/3_wind/3_7_example_ethos_reskit_wind_workflow.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/4_solar/4_1_solar_workflows_overview.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/4_solar/4_2_check_available_pv_modules.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/4_solar/4_3_solar_automated_simulation_workflow.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/5_geothermal/5_run_geothermal_simulations.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/6_direct_air_capture/6_1_direct_air_capture.ipynb
          conda run -n reskit_env jupyter nbconvert --execute --to=python allow-errors=false ./examples/6_direct_air_capture/6_2_cooling_heating.ipynb
